//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_it() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Properties.Resources.it2", typeof(Resources_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cerchio.
        /// </summary>
        internal static string Círculo {
            get {
                return ResourceManager.GetString("Círculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cerchi.
        /// </summary>
        internal static string Círculos {
            get {
                return ResourceManager.GetString("Círculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elenco vuoto di forme!.
        /// </summary>
        internal static string errorEmptyForms {
            get {
                return ResourceManager.GetString("errorEmptyForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forma sconosciuta.
        /// </summary>
        internal static string errorUnknownShape {
            get {
                return ResourceManager.GetString("errorUnknownShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Area.
        /// </summary>
        internal static string outputArea {
            get {
                return ResourceManager.GetString("outputArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perimetro.
        /// </summary>
        internal static string outputPerimeter {
            get {
                return ResourceManager.GetString("outputPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a forme.
        /// </summary>
        internal static string outputShapes {
            get {
                return ResourceManager.GetString("outputShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report forme.
        /// </summary>
        internal static string outputShapesReport {
            get {
                return ResourceManager.GetString("outputShapesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TOTALE.
        /// </summary>
        internal static string outputTotal {
            get {
                return ResourceManager.GetString("outputTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Triangolo.
        /// </summary>
        internal static string outputTriangle {
            get {
                return ResourceManager.GetString("outputTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Triangoli.
        /// </summary>
        internal static string outputTriangles {
            get {
                return ResourceManager.GetString("outputTriangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quadrato.
        /// </summary>
        internal static string Quadrado {
            get {
                return ResourceManager.GetString("Quadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quadrati.
        /// </summary>
        internal static string Quadrados {
            get {
                return ResourceManager.GetString("Quadrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rettangolo.
        /// </summary>
        internal static string Retângulo {
            get {
                return ResourceManager.GetString("Retângulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Trapezio.
        /// </summary>
        internal static string Trapézio {
            get {
                return ResourceManager.GetString("Trapézio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Triangolo scaleno.
        /// </summary>
        internal static string TrianguloEscaleno {
            get {
                return ResourceManager.GetString("TrianguloEscaleno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Triangolo isoscele.
        /// </summary>
        internal static string TrianguloIsosceles {
            get {
                return ResourceManager.GetString("TrianguloIsosceles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Right Triangle.
        /// </summary>
        internal static string TrianguloRetangulo {
            get {
                return ResourceManager.GetString("TrianguloRetangulo", resourceCulture);
            }
        }
    }
}
